export const PRODUCTS = [
  {
    id: "p1",
    name: "Ballpoint Pen",
    categoryId: "c1",
    brand: "PenBrand",
    sku: "WP-123",
    stock: 96,
    price: 1.25,
    description: "Blue ink ballpoint pen.",
    image: "/images/pen.jpg",
  },
  {
    id: "p2",
    name: "A4 Printer Paper (500 sheets)",
    categoryId: "c2",
    brand: "PaperWorks",
    sku: "PP-001",
    stock: 23,
    price: 6.99,
    description: "500 sheets pack of white A4 paper.",
    image: "/images/paper.jpg",
  },
  {
    id: "p3",
    name: "Wireless Mouse",
    categoryId: "c3",
    brand: "TechGear",
    sku: "MO-220",
    stock: 8,
    price: 14.5,
    description: "2.4GHz wireless mouse with USB receiver.",
    image: "/images/mouse.jpg",
  },
  {
    id: "p4",
    name: "Desk Chair",
    categoryId: "c4",
    brand: "FurniCo",
    sku: "DC-777",
    stock: 4,
    price: 89.99,
    description: "Ergonomic office desk chair with armrests.",
    image: "/images/chair.jpg",
  },
  {
    id: "p5",
    name: "Stapler",
    categoryId: "c5",
    brand: "StapleMAX",
    sku: "STP-19B",
    stock: 27,
    price: 4.5,
    description: "Metal stapler for up to 30 sheets.",
    image: "/images/stapler.jpg",
  },
];
